[package]
name = "scha256-ui"
version = "0.1.0"
authors = ["NatrixAeria <upezu@student.kit.edu>"]
edition = "2018"
description = "A web-backend for scha256-engine"

[dependencies]
scha256-engine = { path = "../engine" }
rocket = "0.4"
clap = "3.0.0-beta.2"
